# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            QimingChen
tagline:          Internet Fanatic
url:              http://acming92.github.io
paginate:         1
baseurl:          http://acming92.github.io/
author:
  name:           Qiming Chen
  email:          acming9292@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
